spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/beebeehouse
    username: root
    password: 123456

logging:
  config: logback.xml
  level:
    root: WARN
    org.springframework.web: DEBUG
    org.hibernate: ERROR

# security 配置
security:
  user:
    name: admin
    password: test

