server:
  port: 8082

#spring:
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/beebeehouse
#    username: root
#    password: 123456

logging:
  config: logback.xml
  level:
    root: WARN
    org.springframework.web: DEBUG
    org.hibernate: ERROR

#spring:
#  jpa:
#    hibernate:
#      ddl-auto: update
#  show-sql: true
#  properties:
#    hibernate:
#      format_sql: false
#      use_sql_comments: true

# security 配置
security:
  user:
    name: admin
    password: test

